// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: product.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "product";

export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  stock: number;
  rating: number;
  category: string;
}

export interface ProductReq {
  id: string;
}

export interface ProductRes {
  id: string;
  name: string;
  description: string;
  price: number;
  stock: number;
  category: string;
  rating: number;
}

export interface SearchReq {
  query: string;
  category: string;
  minPrice: number;
  maxPrice: number;
  sort: string;
  page: number;
  limit: number;
}

export interface SearchRes {
  products: Product[];
}

export const PRODUCT_PACKAGE_NAME = "product";

export interface ProductServiceClient {
  getProductById(request: ProductReq): Observable<ProductRes>;

  searchProducts(request: SearchReq): Observable<SearchRes>;
}

export interface ProductServiceController {
  getProductById(request: ProductReq): Promise<ProductRes> | Observable<ProductRes> | ProductRes;

  searchProducts(request: SearchReq): Promise<SearchRes> | Observable<SearchRes> | SearchRes;
}

export function ProductServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getProductById", "searchProducts"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCT_SERVICE_NAME = "ProductService";
