# name: CD - Deploy to EKS

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     name: Deploy to EKS
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}

#       - name: Setup Helm
#         uses: azure/setup-helm@v3
#         with:
#           version: v3.10.0

#       - name: Update Helm dependencies
#         run: helm dependency update charts/ecom

#       - name: Deploy to EKS
#         run: |
#           aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
#           helm upgrade --install ecom charts/ecom --namespace ${{ secrets.EKS_NAMESPACE }} --create-namespace
